### ISSUE TITLE
[BREAKING CHANGE: webpack < 5 used] Errors while running 'yarn development'

### ISSUE THREAD

**Issue by harpreetvirkk** [smartcontractkit/solana-prediction-game#174]
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
        - install 'crypto-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "crypto": false }

ERROR in ./node_modules/cipher-base/index.js 3:16-43
Module not found: Error: Can't resolve 'stream' in '/workspaces/solana-prediction-game/node_modules/cipher-base'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.
<img width="853" alt="Screenshot 2023-02-10 at 12 46 12 AM" src="https://user-images.githubusercontent.com/39559047/217915991-43e3f4d2-7ad0-45c5-bb56-cb2168aa52d9.png">

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "stream": require.resolve("stream-browserify") }'
        - install 'stream-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "stream": false }

**Comment by dustinsgoodman** [comment]
Hey @harpreetvirkk, I just posted PR #177 to resolve this for future users, but it requires a change to your Vercel setup. If you go to your project's "Settings" page in Vercel and update the "Build & Development Settings" so that the "Development Command" uses `react-app-rewired start` as an override, you should see this issue disappear. The PR I added will set up all future projects using the Vercel CLI with these default settings, but it doesn't update existing projects, unfortunately.

Please let me know if you have any questions.

<img width="920" alt="image" src="https://user-images.githubusercontent.com/1815379/221315620-c7c2166d-7f0f-433b-a379-d6e866096530.png">
